name: FastAPI CI (uv + make)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # 或 3.12

      - name: Install uv
        run: pipx install uv

      - name: Cache uv and venv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            apps/ai/.venv
          key: uv-${{ runner.os }}-${{ hashFiles('apps/ai/pyproject.toml', 'apps/ai/uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-

      - name: Sync deps (with dev extras)
        working-directory: apps/ai
        run: uv sync --extra dev --frozen || uv sync --extra dev

      - name: Run all checks
        working-directory: apps/ai
        run: PYTHONPATH=. make check-all
